* Refactored Heat templates folders * Updated templates parameter names, added endpoints

diff --git a/production-templates/paas/biaas/pentaho/pentaho-server-postgresql-float-ip.template b/production-templates/paas/biaas/pentaho/pentaho-server-postgresql-float-ip.template
--- a/production-templates/paas/biaas/pentaho/pentaho-server-postgresql-float-ip.template
+++ b/production-templates/paas/biaas/pentaho/pentaho-server-postgresql-float-ip.template
@@ -1,44 +1,33 @@
 heat_template_version: 2013-05-23
 
-description: Template to deploy a Pentaho Client with Data Integration and Report Design Tools
+description: Template to deploy a single user data instance (jdk7 + Pentaho 5.1 + PostgreSQL 9.3)
 
 parameters:
   key_name:
     type: string
-    description: Name of a KeyPair
-  user_public_key:
-    type: string
-    description: public user key  
+    description: Name of a KeyPair 
   vm_name:
     type: string
     label: VM name
-  instance_type:
+  flavor:
     type: string
     label: Instance Type
-    description: Type of instance (flavor) to be used
+    description: Type of instance (flavor) to be used-large.bronze for extern
     default: large.bronze
   availability_zone:
     type: string
     description: The Availability Zone to launch the instance.
     default: nova
-  ext_net_id:
+  networks:
+    type: json
+    description: list of network IDs (in json format) into which the server will be deployed
+  float_net_id:
     type: string
-    description: ID of public sub network into which servers get deployed
-  private_net_id:
-    type: string
-    description: ID of private sub network into which servers get deployed
+    description: ID of the external network
   security_groups:
     type: comma_delimited_list
     description: List of security group names or IDs
     default: [biaas,zabbix]
-  design_user:
-    type: string
-    description: Designer account username
-    default: admin
-  design_password:
-    type: string
-    description: Designer account password
-    hidden: true
   admin_password:
     type: string
     description: Password for Administration
@@ -60,6 +49,15 @@ parameters:
     description: the base URL of the auxiliary HTTP repository containing template add-ons files
     constraints:
       - allowed_pattern: "^https?://.*"
+  pentaho_port:
+    type: number
+    description: "The port for Pentaho service"
+  zabbix_servers_dn:
+    description: "A CSV list of Zabbix servers domain name"
+    type: string
+  puppet_server_dn:
+    description: "The Puppet master domain name"
+    type: string
 
 
 resources:
@@ -76,42 +74,54 @@ resources:
     properties:
       name: { get_param: vm_name }
       key_name: { get_param: key_name }
-      image: PRISMA-Ubuntu-14.04-x86_64-Desktop
-      flavor: { get_param: instance_type }
+      image: PRISMA-Ubuntu-14.04-x86_64
+      flavor: { get_param: flavor }
       availability_zone: { get_param: availability_zone }
-      networks:
-        - port: { get_resource: user_data_instance_port }
+      networks: { get_param: networks }
+      security_groups: { get_param: security_groups}
       user_data_format: RAW
       user_data:
         str_replace:
+          params:
+            pentahopassword: {get_attr: [pentaho_user_passwd, value]}
+            admin_password: { get_param: admin_password }
+            db_rootpassword: {get_attr: [postgres_root_passwd, value]}
+            aux_repo_url: { get_param: aux_repo_url }
+            mountpoint: { get_param: mountpoint }
+            volume_id: { get_resource: cinder_volume }
+            zabbix_servers_dn: { get_param: zabbix_servers_dn }
+            puppet_server_dn: { get_param: puppet_server_dn }
+            $wait_handle$: { get_resource: wait_condition_handle}
           template: |
             #!/bin/bash -v
             # Helper function to signal error condition
             function notify_err
             {
              message=$1
-             curl -X PUT -H 'Content-Type:application/json' -d "{\"Status\" : \"FAILURE\",\"Reason\" : \"$message\",\"UniqueId\" : \"ID1\",\"Data\" : \"Server Configuration NOT OK\"}" \
+             curl -k -X PUT -H 'Content-Type:application/json' -d "{\"Status\" : \"FAILURE\",\"Reason\" : \"$message\",\"UniqueId\" : \"ID1\",\"Data\" : \"Server Configuration NOT OK\"}" \
              "$wait_handle$"
              exit 1
             }
             sudo su -
+
+            # Configure the network interfaces, if needed
+            interfaces=$(ip link show | grep -Eo "[1-9]: [a-z0-9]+:" | grep -Ev "(lo|eth0)" | cut -d: -f2)
+
+            for i in ${interfaces[@]}; do
+                if [ -e /etc/network/interfaces.d/eth0.cfg ]; then
+                   sed "s/eth0/$i/g" /etc/network/interfaces.d/eth0.cfg  > /etc/network/interfaces.d/$i.cfg
+                fi
+                ifdown $i; ifup $i
+            done
+
             # Create Linux User Account
             useradd -s /bin/bash -m pentaho
-            echo "pentaho:root_password" | chpasswd
+            echo "pentaho:pentahopassword" | chpasswd
             mkdir -p /home/pentaho/server/biserver-ce
             mkdir -p .pentaho
-            mkdir -p /home/pentaho/client
-            mkdir /home/pentaho/Desktop
-            chown pentaho:pentaho /home/pentaho/Desktop
-            chmod 755 /home/pentaho/Desktop
-            sed -i "s:^127.0.0.1:127.0.0.1 $HOSTNAME:" /etc/hosts
-            mkdir /home/pentaho/.ssh
-            chmod 700 /home/pentaho/.ssh
-            echo "user_public_key"  >> /home/pentaho/.ssh/authorized_keys
-            chmod 600 /home/pentaho/.ssh/authorized_keys
-            chown pentaho:pentaho /home/pentaho/.ssh
-            chown pentaho:pentaho /home/pentaho/.ssh/authorized_keys
+            echo 'pentaho ALL=(ALL) ALL' | sudo tee -a /etc/sudoers
             apt-get update 
+            sed -i "s:^127.0.0.1:127.0.0.1 $HOSTNAME:" /etc/hosts
             apt-get install -y openssh-server openssl bash libssl1.0.0
             #install jdk
             apt-get install -y openjdk-7-jdk 
@@ -143,11 +153,16 @@ resources:
             sed -i "s|connect.*$|connect quartz postgres|g" /home/pentaho/server/biserver-ce/data/postgresql/create_repository_postgresql.sql
             sed -i "s|connect.*$|connect quartz postgres|g" /home/pentaho/server/biserver-ce/data/postgresql/create_jcr_postgresql.sql
 
+
             #Allow user to use volume
+            voldata_id=volume_id
+            voldata_dev="/dev/disk/by-id/virtio-$(echo ${voldata_id} | cut -c -20)"
             mkdir -p mountpoint
-            mkfs.ext4 device_name && mount device_name mountpoint || notify_err "Some problems occurred with block device"
+            mkfs.ext4 ${voldata_dev} && mount ${voldata_dev} mountpoint || notify_err "Some problems occurred with block device"
             echo "Successfully device mounted"
-            echo 'device_name mountpoint ext4 defaults 0 0' >> /etc/fstab
+            #For reboot instance
+            echo "${voldata_dev} mountpoint ext4 defaults 0 0" >> /etc/fstab
+
             mkdir mountpoint/data
             chmod -R 0755 mountpoint
 
@@ -221,7 +236,7 @@ resources:
             wget --no-check-certificate aux_repo_url/pentaho-5.1/conf/pentaho -O /etc/init.d/pentaho
             #import already ad-hoc modified version of start-pentaho.sh
             mv /home/pentaho/server/biserver-ce/start-pentaho.sh /home/pentaho/server/biserver-ce/start-pentaho.sh.OLD
-            wget --no-check-certificate aux_repo_url/pentaho-5.1/conf/start-pentaho.sh -O /home/pentaho/server/biserver-ce/start-pentaho.sh
+            wget --no-check-certificate aux_repo_url//pentaho-5.1/conf/start-pentaho.sh -O /home/pentaho/server/biserver-ce/start-pentaho.sh
             chmod 777 /home/pentaho/server/biserver-ce/*.sh
             chmod +x /etc/init.d/pentaho
             update-rc.d pentaho defaults
@@ -257,114 +272,29 @@ resources:
             # change default admin password
             curl -u admin:password -X PUT -H"Content-Type: application/json" -d '{"userName": "admin", "password" : "admin_password"}' http://127.0.0.1:8080/pentaho/api/userroledao/updatePassword
 
-
-            #Install x2go
-            sudo add-apt-repository ppa:x2go/stable
-            sudo apt-get update
-            sudo apt-get install -y x2goserver x2goserver-xsession
-            #Install zip e unzip
-            apt-get install -y zip unzip 
-            # Install jdk
-            apt-get install -y openjdk-7-jdk
-            su root -c "echo 'export PENTAHO_JAVA_HOME=\"/usr/lib/jvm//java-7-openjdk-amd64\"' >> /etc/environment" 
-            # Install Pentaho Report Designer
-            wget --no-check-certificate aux_repo_url/pentaho-5.1/packages/prd-ce-5.1.0.0-752.zip
-            [[ $? -eq 0 ]] || notify_err "Some problems occurred with Install Pentaho Report Designer"
-            unzip -n prd-ce-5.1.0.0-752.zip -d /home/pentaho/client
-            # Install Pentaho Data Integration (Kettle)
-            wget --no-check-certificate aux_repo_url/pentaho-5.1/packages/pdi-ce-5.1.0.0-752.zip
-            [[ $? -eq 0 ]] || notify_err "Some problems occurred with Install Pentaho Data Integration "
-            unzip -n pdi-ce-5.1.0.0-752.zip -d /home/pentaho/client
-            # Install Postgresql driver
-            wget --no-check-certificate -O /home/pentaho/client/report-designer/lib/jdbc/postgresql-9.2-1003.jdbc4.jar aux_repo_url/pentaho-5.1/packages/postgresql-9.2-1003.jdbc4.jar
-            [[ $? -eq 0 ]] || notify_err "Some problems occurred with Install Postgresql driver "
-            #Install Mysql Driver
-            wget --no-check-certificate aux_repo_url/pentaho-5.1/packages/mysql-connector-java-5.1.17-bin.jar.zip
-            [[ $? -eq 0 ]] || notify_err "Some problems occurred with Install Mysql driver "
-            unzip -n mysql-connector-java-5.1.17-bin.jar.zip -d /home/pentaho/client/report-designer/lib/jdbc/ 
-            unzip -n mysql-connector-java-5.1.17-bin.jar.zip -d /home/pentaho/client/data-integration/lib/  
-            # Configure existing Pentaho server as Report Designer Repository (IP:8080/pentaho is the default configuration)
-            #sed -i "s|localhost|ip_server_bi|g" /home/pentaho/client/report-designer/resources/classic-engine.properties
-            sed -i "s|Designer|design_user|g" /home/pentaho/client/report-designer/resources/classic-engine.properties
-            sed -i "s|roles=None|roles=manager-gui,admin-gui|g" /home/pentaho/client/report-designer/resources/classic-engine.properties
-            sed -i "s|password|design_password|g" /home/pentaho/client/report-designer/resources/report-designer.properties
-            #sed -i "s|localhost|ip_server_bi|g" /home/pentaho/client/report-designer/resources/report-designer.properties
-            # Set configuration for better performance
-            sed -i "s|-XX:MaxPermSize=512m|-XX:MaxPermSize=512m -Xmx1024M|g" /home/pentaho/client/report-designer/report-designer.sh
-            # Create desktop icon for App launching
-            cat << EOF > /usr/share/applications/pentaho-prd.desktop
-            [Desktop Entry]
-            Version=1.0
-            Name=Pentaho-Reporting
-            Comment=Pentaho Reporting App
-            Exec=/usr/bin/launch_pentaho_report.sh
-            Icon=/home/pentaho/client/data-integration/docs/English/welcome/img/header-image-1.png
-            Terminal=false
-            Type=Application
-            Categories=Utility;Application;
-            EOF
-            ########
-            cat << EOF > /usr/share/applications/pentaho-pdi.desktop
-            [Desktop Entry]
-            Version=1.0
-            Name=Pentaho-Data-Integration
-            Comment=Pentaho ETL App
-            Exec=/usr/bin/launch_pentaho_pdi.sh
-            Icon=/home/pentaho/client/data-integration/docs/English/welcome/img/header-image-2.png
-            Terminal=false
-            Type=Application
-            Categories=Utility;Application;
-            EOF
-            #######
-            cat << EOF > /usr/bin/launch_pentaho_report.sh
-            #!/bin/bash
-            unset PENTAHO_JAVA_HOME PENTAHO_JAVA
-            cd /home/pentaho/client/report-designer
-            ./report-designer.sh
-            EOF
-            #######
-            cat << EOF > /usr/bin/launch_pentaho_pdi.sh
-            #!/bin/bash
-            unset PENTAHO_JAVA_HOME PENTAHO_JAVA
-            cd /home/pentaho/client/data-integration
-            ./spoon.sh
-            EOF
-            cp -f /usr/share/applications/pentaho-pdi.desktop /home/pentaho/Desktop/pentaho-pdi.desktop
-            chown pentaho:pentaho /home/pentaho/Desktop/pentaho-pdi.desktop
-            chmod +x /home/pentaho/Desktop/pentaho-pdi.desktop
-            chmod 755 /usr/bin/launch_pentaho_pdi.sh
-            cp -f /usr/share/applications/pentaho-prd.desktop /home/pentaho/Desktop/pentaho-prd.desktop
-            chown pentaho:pentaho /home/pentaho/Desktop/pentaho-prd.desktop
-            chmod +x /home/pentaho/Desktop/pentaho-prd.desktop
-            chmod 755 /usr/bin/launch_pentaho_report.sh
-
             # Zabbix agent installation
-            echo "Zabbix Agent installation and configuration"
-            wget --no-check-certificate http://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+trusty_all.deb
+            echo "Zabbix Agent setup"
+            wget http://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+trusty_all.deb
             dpkg -i zabbix-release_2.2-1+trusty_all.deb
             apt-get update
             apt-get install -y zabbix-agent
-            zabbix_metrics="zabbix-metrics.infn.ponsmartcities-prisma.it"
-            zabbix_watcher="zabbix-watcher.infn.ponsmartcities-prisma.it"
-            sed -i -e "s/^Server=.*/Server=${zabbix_metrics},${zabbix_watcher}/" /etc/zabbix/zabbix_agentd.conf
-            sed -i -e "s/^ServerActive=.*/ServerActive=${zabbix_metrics},${zabbix_watcher}/" /etc/zabbix/zabbix_agentd.conf
+            sed -i -e "s/^Server=.*/Server=zabbix_servers_dn/" /etc/zabbix/zabbix_agentd.conf
+            sed -i -e "s/^ServerActive=.*/ServerActive=zabbix_servers_dn/" /etc/zabbix/zabbix_agentd.conf
             sed -i -e "s/^Hostname=.*/Hostname=${HOSTNAME//./_}/" /etc/zabbix/zabbix_agentd.conf
-            service zabbix-agent restart || notify_err "Some problems occurred with Zabbix Agent installation/configuration"
+            service zabbix-agent restart || notify_err "Some problems occurred with Zabbix Agent setup"
 
-            curl -X PUT -H 'Content-Type:application/json' -d '{"Status" : "SUCCESS","Reason" : "BI Client Tools and BI Server installed OK","UniqueId" : "ID1","Data" : "Server Configuration OK"}' \
-            "$wait_handle$" 
+            # Puppet agent installation
+            echo "Puppet agent installation and configuration"
+            wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
+            dpkg -i puppetlabs-release-trusty.deb
+            apt-get update
+            apt-get install -y puppet
+            puppet agent --server puppet_server_dn --onetime --no-daemonize --verbose
+            #[[ $? -eq 0 ]] || notify_err "Puppet agent failed. See logs for details"
+
+            curl -k -X PUT -H 'Content-Type:application/json' -d '{"Status" : "SUCCESS","Reason" : "Pentaho with Postgresql installed OK","UniqueId" : "ID1","Data" : "Server Configuration OK"}' \
+            "$wait_handle$"     
             exit 0
-          params:
-            db_rootpassword: {get_attr: [postgres_root_passwd, value]}
-            root_password: {get_attr: [pentaho_user_passwd, value]}
-            admin_password: { get_param: admin_password } 
-            aux_repo_url: { get_param: aux_repo_url }
-            design_user: { get_param: design_user }
-            design_password: { get_param: design_password }
-            mountpoint: { get_param: mountpoint }
-            device_name: /dev/vdb
-            $wait_handle$: { get_resource: wait_condition_handle}
-            user_public_key: { get_param: user_public_key }
 
   wait_condition:
     type: AWS::CloudFormation::WaitCondition
@@ -372,7 +302,7 @@ resources:
     properties:
      Count: 1
      Handle: { get_resource: wait_condition_handle }
-     Timeout: 7000
+     Timeout: 3500
 
   wait_condition_handle:
            type: AWS::CloudFormation::WaitConditionHandle
@@ -383,47 +313,52 @@ resources:
       size: { get_param: volume_size }
       availability_zone: { get_param: availability_zone }
       volume_type: { get_param: volume_type }
+
   volume_attachment:
     type: OS::Cinder::VolumeAttachment
     properties:
       volume_id: { get_resource: cinder_volume }
       instance_uuid: { get_resource: user_data_instance }
-      mountpoint: /dev/vdb
+      mountpoint: null
 
-  user_data_instance_port:
-    type: OS::Neutron::Port
-    properties:
-      network_id: { get_param: private_net_id }
-      security_groups: { get_param: security_groups }
-
-  user_data_instance_floating_ip:
+  floating_ip:
     type: OS::Neutron::FloatingIP
     properties:
-      floating_network_id: { get_param: ext_net_id }
-      port_id: { get_resource: user_data_instance_port }
+      floating_network_id: { get_param: float_net_id }
 
+  instance_floating_ip:
+    type: OS::Nova::FloatingIPAssociation
+    properties:
+      floating_ip: { get_resource: floating_ip }
+      server_id: { get_resource: user_data_instance }
+  
 outputs:
-  instance_public_ip:
-    description: Floating IP address of deployed instance in public network
-    value: { get_attr: [ user_data_instance_floating_ip, floating_ip_address ] }
   instance_id:
     description: Resource ID assigned to the newly created instance
     value: { get_resource: user_data_instance }
-  manage_url: 
-    description: Pentaho BI Community Edition can be accessed at 
+
+  instance_ips:
+    description: The IP address of the deployed instance
+    value: { get_attr: [user_data_instance, networks] }
+
+  instance_floating_ip:
+    description: Floating IP address of deployed instance in public network
+    value: { get_attr: [ floating_ip, floating_ip_address ] }
+
+  endpoints:
+    description: "Service endpoints"
     value:
-      str_replace:
-        template: http://host:8080/pentaho
-        params:
-          host: { get_attr: [ user_data_instance_floating_ip, floating_ip_address ] }
-  postgres_root_passwd:
-    description: Password for PostgreSQL root user 
+      "pentaho":
+        str_replace:
+          params:
+            host: { get_attr: [ floating_ip, floating_ip_address ] }
+            pentaho_port: { get_param: pentaho_port }
+          template: "http://host:pentaho_port/pentaho"
+ 
+  postgresql_root_password:
+    description: Password for PostgreSQL root user
     value: {  get_resource: postgres_root_passwd }
-  pentaho_user_passwd:
-    description: Password for pentaho Linux user  
-    value: { get_resource: pentaho_user_passwd} 
-
-        
-
-
-
+  
+  pentaho_user_password:
+    description: Password for pentaho Linux user       
+    value: { get_resource: pentaho_user_passwd}
diff --git a/production-templates/paas/biaas/pentaho/pentaho-server-postgresql.template b/production-templates/paas/biaas/pentaho/pentaho-server-postgresql.template
--- a/production-templates/paas/biaas/pentaho/pentaho-server-postgresql.template
+++ b/production-templates/paas/biaas/pentaho/pentaho-server-postgresql.template
@@ -21,9 +21,6 @@ parameters:
   networks:
     type: json
     description: list of network IDs (in json format) into which the server will be deployed
-  float_net_id:
-    type: string
-    description: ID of the external network
   security_groups:
     type: comma_delimited_list
     description: List of security group names or IDs
@@ -59,7 +56,6 @@ parameters:
     description: "The Puppet master domain name"
     type: string
 
-
 resources:
   postgres_root_passwd: 
     type: OS::Heat::RandomString
@@ -77,11 +73,21 @@ resources:
       image: PRISMA-Ubuntu-14.04-x86_64
       flavor: { get_param: flavor }
       availability_zone: { get_param: availability_zone }
-      networks: { get_param: networks }
+      networks: { get_param: networks} 
       security_groups: { get_param: security_groups}
       user_data_format: RAW
       user_data:
         str_replace:
+          params:
+            pentahopassword: {get_attr: [pentaho_user_passwd, value]}
+            admin_password: { get_param: admin_password }
+            db_rootpassword: {get_attr: [postgres_root_passwd, value]}
+            aux_repo_url: { get_param: aux_repo_url }
+            mountpoint: { get_param: mountpoint }
+            volume_id: { get_resource: cinder_volume }
+            zabbix_servers_dn: { get_param: zabbix_servers_dn }
+            puppet_server_dn: { get_param: puppet_server_dn }
+            $wait_handle$: { get_resource: wait_condition_handle}
           template: |
             #!/bin/bash -v
             # Helper function to signal error condition
@@ -94,15 +100,15 @@ resources:
             }
             sudo su -
 
-              # Configure the network interfaces, if needed
-              interfaces=$(ip link show | grep -Eo "[1-9]: [a-z0-9]+:" | grep -Ev "(lo|eth0)" | cut -d: -f2)
+            # Configure the network interfaces, if needed
+            interfaces=$(ip link show | grep -Eo "[1-9]: [a-z0-9]+:" | grep -Ev "(lo|eth0)" | cut -d: -f2)
 
-              for i in ${interfaces[@]}; do
+            for i in ${interfaces[@]}; do
                 if [ -e /etc/network/interfaces.d/eth0.cfg ]; then
                    sed "s/eth0/$i/g" /etc/network/interfaces.d/eth0.cfg  > /etc/network/interfaces.d/$i.cfg
                 fi
                 ifdown $i; ifup $i
-              done
+            done
 
             # Create Linux User Account
             useradd -s /bin/bash -m pentaho
@@ -143,7 +149,6 @@ resources:
             sed -i "s|connect.*$|connect quartz postgres|g" /home/pentaho/server/biserver-ce/data/postgresql/create_repository_postgresql.sql
             sed -i "s|connect.*$|connect quartz postgres|g" /home/pentaho/server/biserver-ce/data/postgresql/create_jcr_postgresql.sql
 
-
             #Allow user to use volume
             voldata_id=volume_id
             voldata_dev="/dev/disk/by-id/virtio-$(echo ${voldata_id} | cut -c -20)"
@@ -152,7 +157,7 @@ resources:
             echo "Successfully device mounted"
             #For reboot instance
             echo "${voldata_dev} mountpoint ext4 defaults 0 0" >> /etc/fstab
-
+            
             mkdir mountpoint/data
             chmod -R 0755 mountpoint
 
@@ -226,7 +231,7 @@ resources:
             wget --no-check-certificate aux_repo_url/pentaho-5.1/conf/pentaho -O /etc/init.d/pentaho
             #import already ad-hoc modified version of start-pentaho.sh
             mv /home/pentaho/server/biserver-ce/start-pentaho.sh /home/pentaho/server/biserver-ce/start-pentaho.sh.OLD
-            wget --no-check-certificate aux_repo_url//pentaho-5.1/conf/start-pentaho.sh -O /home/pentaho/server/biserver-ce/start-pentaho.sh
+            wget --no-check-certificate aux_repo_url/pentaho-5.1/conf/start-pentaho.sh -O /home/pentaho/server/biserver-ce/start-pentaho.sh
             chmod 777 /home/pentaho/server/biserver-ce/*.sh
             chmod +x /etc/init.d/pentaho
             update-rc.d pentaho defaults
@@ -252,7 +257,7 @@ resources:
             else
               let MY_CHECK-=1
             fi
-            sleep 5;
+            sleep 1;
             done
             # Delete default user pat, suzy, tiffany
             curl -u admin:password -X PUT -H"Content-Type: application/json" http://127.0.0.1:8080/pentaho/api/userroledao/deleteUsers?userNames=tiffany
@@ -263,41 +268,29 @@ resources:
             curl -u admin:password -X PUT -H"Content-Type: application/json" -d '{"userName": "admin", "password" : "admin_password"}' http://127.0.0.1:8080/pentaho/api/userroledao/updatePassword
 
 
+            # Zabbix agent installation
+            echo "Zabbix Agent setup"
+            wget http://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+trusty_all.deb
+            dpkg -i zabbix-release_2.2-1+trusty_all.deb
+            apt-get update
+            apt-get install -y zabbix-agent
+            sed -i -e "s/^Server=.*/Server=zabbix_servers_dn/" /etc/zabbix/zabbix_agentd.conf
+            sed -i -e "s/^ServerActive=.*/ServerActive=zabbix_servers_dn/" /etc/zabbix/zabbix_agentd.conf
+            sed -i -e "s/^Hostname=.*/Hostname=${HOSTNAME//./_}/" /etc/zabbix/zabbix_agentd.conf
+            service zabbix-agent restart || notify_err "Some problems occurred with Zabbix Agent setup"
 
-              # Zabbix agent installation
-              echo "Zabbix Agent setup"
-              wget http://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+trusty_all.deb
-              dpkg -i zabbix-release_2.2-1+trusty_all.deb
-              apt-get update
-              apt-get install -y zabbix-agent
-              sed -i -e "s/^Server=.*/Server=zabbix_servers_dn/" /etc/zabbix/zabbix_agentd.conf
-              sed -i -e "s/^ServerActive=.*/ServerActive=zabbix_servers_dn/" /etc/zabbix/zabbix_agentd.conf
-              sed -i -e "s/^Hostname=.*/Hostname=${HOSTNAME//./_}/" /etc/zabbix/zabbix_agentd.conf
-              service zabbix-agent restart || notify_err "Some problems occurred with Zabbix Agent setup"
-
-              # Puppet agent installation
-              echo "Puppet agent installation and configuration"
-              wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
-              dpkg -i puppetlabs-release-trusty.deb
-              apt-get update
-              apt-get install -y puppet
-              puppet agent --server puppet_server_dn --onetime --no-daemonize --verbose
-              #[[ $? -eq 0 ]] || notify_err "Puppet agent failed. See logs for details"
-
+            # Puppet agent installation
+            echo "Puppet agent installation and configuration"
+            wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
+            dpkg -i puppetlabs-release-trusty.deb
+            apt-get update
+            apt-get install -y puppet
+            puppet agent --server puppet_server_dn --onetime --no-daemonize --verbose
+            #[[ $? -eq 0 ]] || notify_err "Puppet agent failed. See logs for details"
 
             curl -k -X PUT -H 'Content-Type:application/json' -d '{"Status" : "SUCCESS","Reason" : "Pentaho with Postgresql installed OK","UniqueId" : "ID1","Data" : "Server Configuration OK"}' \
             "$wait_handle$"     
             exit 0
-          params:
-            pentahopassword: {get_attr: [pentaho_user_passwd, value]}
-            admin_password: { get_param: admin_password }
-            db_rootpassword: {get_attr: [postgres_root_passwd, value]}
-            aux_repo_url: { get_param: aux_repo_url }
-            mountpoint: { get_param: mountpoint }
-            volume_id: { get_resource: cinder_volume }
-            zabbix_servers_dn: { get_param: zabbix_servers_dn }
-            puppet_server_dn: { get_param: puppet_server_dn }
-            $wait_handle$: { get_resource: wait_condition_handle}
 
   wait_condition:
     type: AWS::CloudFormation::WaitCondition
@@ -324,50 +317,30 @@ resources:
       instance_uuid: { get_resource: user_data_instance }
       mountpoint: null
 
-  floating_ip:
-    type: OS::Neutron::FloatingIP
-    properties:
-      floating_network_id: { get_param: float_net_id }
 
-  instance_floating_ip:
-    type: OS::Nova::FloatingIPAssociation
-    properties:
-      floating_ip: { get_resource: floating_ip }
-      server_id: { get_resource: user_data_instance }
-
-
-  
 outputs:
+  instance_id:
+    description: Resource ID assigned to the newly created instance
+    value: { get_resource: user_data_instance }
 
   instance_ips:
     description: The IP address of the deployed instance
     value: { get_attr: [user_data_instance, networks] }
 
-  instance_floating_ip:
-    description: Floating IP address of deployed instance in public network
-    value: { get_attr: [ floating_ip, floating_ip_address ] }
-
   endpoints:
     description: "Service endpoints"
     value:
-      "Pentaho Web UI":
+      "pentaho":
         str_replace:
           params:
-            host: { get_attr: [ floating_ip, floating_ip_address ] }
+            host: { get_attr: [user_data_instance, first_address] }
             pentaho_port: { get_param: pentaho_port }
           template: "http://host:pentaho_port/pentaho"
 
-  instance_id:
-    description: Resource ID assigned to the newly created instance
-    value: { get_resource: user_data_instance }
-  
-  postgres_root_passwd:
+  postgresql_root_password:
     description: Password for PostgreSQL root user
     value: {  get_resource: postgres_root_passwd }
   
-  pentaho_user_passwd:
+  pentaho_user_password:
     description: Password for pentaho Linux user       
     value: { get_resource: pentaho_user_passwd}
-
-
-
