Diffuse changes. Major: multiple NIC management, automatic device selection

diff --git a/production-templates/paas/biaas/pentahoserver-postgresql.template b/production-templates/paas/biaas/pentahoserver-postgresql.template
--- a/production-templates/paas/biaas/pentahoserver-postgresql.template
+++ b/production-templates/paas/biaas/pentahoserver-postgresql.template
@@ -9,7 +9,7 @@ parameters:
   vm_name:
     type: string
     label: VM name
-  instance_type:
+  flavor:
     type: string
     label: Instance Type
     description: Type of instance (flavor) to be used-large.bronze for extern
@@ -18,9 +18,9 @@ parameters:
     type: string
     description: The Availability Zone to launch the instance.
     default: nova
-  net_id:
-    type: string
-    description: ID of public (or private) sub network into which servers get deployed
+  networks:
+    type: json
+    description: list of network IDs (in json format) into which the server will be deployed
   security_groups:
     type: comma_delimited_list
     description: List of security group names or IDs
@@ -46,6 +46,15 @@ parameters:
     description: the base URL of the auxiliary HTTP repository containing template add-ons files
     constraints:
       - allowed_pattern: "^https?://.*"
+  pentaho_port:
+    type: number
+    description: "The port for Pentaho service"
+  zabbix_servers_dn:
+    description: "A CSV list of Zabbix servers domain name"
+    type: string
+  puppet_server_dn:
+    description: "The Puppet master domain name"
+    type: string
 
 resources:
   postgres_root_passwd: 
@@ -62,10 +71,10 @@ resources:
       name: { get_param: vm_name }
       key_name: { get_param: key_name }
       image: PRISMA-Ubuntu-14.04-x86_64
-      flavor: { get_param: instance_type }
+      flavor: { get_param: flavor }
       availability_zone: { get_param: availability_zone }
-      networks:
-        - port: { get_resource: user_data_instance_port }
+      networks: { get_param: networks} 
+      security_groups: { get_param: security_groups}
       user_data_format: RAW
       user_data:
         str_replace:
@@ -75,11 +84,22 @@ resources:
             function notify_err
             {
              message=$1
-             curl -X PUT -H 'Content-Type:application/json' -d "{\"Status\" : \"FAILURE\",\"Reason\" : \"$message\",\"UniqueId\" : \"ID1\",\"Data\" : \"Server Configuration NOT OK\"}" \
+             curl -k -X PUT -H 'Content-Type:application/json' -d "{\"Status\" : \"FAILURE\",\"Reason\" : \"$message\",\"UniqueId\" : \"ID1\",\"Data\" : \"Server Configuration NOT OK\"}" \
              "$wait_handle$"
              exit 1
             }
             sudo su -
+
+              # Configure the network interfaces, if needed
+              interfaces=$(ip link show | grep -Eo "[1-9]: [a-z0-9]+:" | grep -Ev "(lo|eth0)" | cut -d: -f2)
+
+              for i in ${interfaces[@]}; do
+                if [ -e /etc/network/interfaces.d/eth0.cfg ]; then
+                   sed "s/eth0/$i/g" /etc/network/interfaces.d/eth0.cfg  > /etc/network/interfaces.d/$i.cfg
+                fi
+                ifdown $i; ifup $i
+              done
+
             # Create Linux User Account
             useradd -s /bin/bash -m pentaho
             echo "pentaho:pentahopassword" | chpasswd
@@ -120,10 +140,14 @@ resources:
             sed -i "s|connect.*$|connect quartz postgres|g" /home/pentaho/server/biserver-ce/data/postgresql/create_jcr_postgresql.sql
 
             #Allow user to use volume
+            voldata_id=volume_id
+            voldata_dev="/dev/disk/by-id/virtio-$(echo ${voldata_id} | cut -c -20)"
             mkdir -p mountpoint
-            mkfs.ext4 device_name && mount device_name mountpoint || notify_err "Some problems occurred with block device"
+            mkfs.ext4 ${voldata_dev} && mount ${voldata_dev} mountpoint || notify_err "Some problems occurred with block device"
             echo "Successfully device mounted"
-            echo 'device_name mountpoint ext4 defaults 0 0' >> /etc/fstab
+            #For reboot instance
+            echo "${voldata_dev} mountpoint ext4 defaults 0 0" >> /etc/fstab
+            
             mkdir mountpoint/data
             chmod -R 0755 mountpoint
 
@@ -234,20 +258,27 @@ resources:
             curl -u admin:password -X PUT -H"Content-Type: application/json" -d '{"userName": "admin", "password" : "admin_password"}' http://127.0.0.1:8080/pentaho/api/userroledao/updatePassword
 
 
-            # Zabbix agent installation
-            echo "Zabbix Agent installation and configuration"
-            wget --no-check-certificate http://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+trusty_all.deb
-            dpkg -i zabbix-release_2.2-1+trusty_all.deb
-            apt-get update
-            apt-get install -y zabbix-agent
-            zabbix_metrics="zabbix-metrics.infn.ponsmartcities-prisma.it"
-            zabbix_watcher="zabbix-watcher.infn.ponsmartcities-prisma.it"
-            sed -i -e "s/^Server=.*/Server=${zabbix_metrics},${zabbix_watcher}/" /etc/zabbix/zabbix_agentd.conf
-            sed -i -e "s/^ServerActive=.*/ServerActive=${zabbix_metrics},${zabbix_watcher}/" /etc/zabbix/zabbix_agentd.conf
-            sed -i -e "s/^Hostname=.*/Hostname=${HOSTNAME//./_}/" /etc/zabbix/zabbix_agentd.conf
-            service zabbix-agent restart || notify_err "Some problems occurred with Zabbix Agent installation/configuration"
+              # Zabbix agent installation
+              echo "Zabbix Agent setup"
+              wget http://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+trusty_all.deb
+              dpkg -i zabbix-release_2.2-1+trusty_all.deb
+              apt-get update
+              apt-get install -y zabbix-agent
+              sed -i -e "s/^Server=.*/Server=zabbix_servers_dn/" /etc/zabbix/zabbix_agentd.conf
+              sed -i -e "s/^ServerActive=.*/ServerActive=zabbix_servers_dn/" /etc/zabbix/zabbix_agentd.conf
+              sed -i -e "s/^Hostname=.*/Hostname=${HOSTNAME//./_}/" /etc/zabbix/zabbix_agentd.conf
+              service zabbix-agent restart || notify_err "Some problems occurred with Zabbix Agent setup"
 
-            curl -X PUT -H 'Content-Type:application/json' -d '{"Status" : "SUCCESS","Reason" : "Pentaho with Postgresql installed OK","UniqueId" : "ID1","Data" : "Server Configuration OK"}' \
+              # Puppet agent installation
+              echo "Puppet agent installation and configuration"
+              wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
+              dpkg -i puppetlabs-release-trusty.deb
+              apt-get update
+              apt-get install -y puppet
+              puppet agent --server puppet_server_dn --onetime --no-daemonize --verbose
+              #[[ $? -eq 0 ]] || notify_err "Puppet agent failed. See logs for details"
+
+            curl -k -X PUT -H 'Content-Type:application/json' -d '{"Status" : "SUCCESS","Reason" : "Pentaho with Postgresql installed OK","UniqueId" : "ID1","Data" : "Server Configuration OK"}' \
             "$wait_handle$"     
             exit 0
           params:
@@ -256,7 +287,9 @@ resources:
             db_rootpassword: {get_attr: [postgres_root_passwd, value]}
             aux_repo_url: { get_param: aux_repo_url }
             mountpoint: { get_param: mountpoint }
-            device_name: /dev/vdb
+            volume_id: { get_resource: cinder_volume }
+            zabbix_servers_dn: { get_param: zabbix_servers_dn }
+            puppet_server_dn: { get_param: puppet_server_dn }
             $wait_handle$: { get_resource: wait_condition_handle}
 
   wait_condition:
@@ -276,36 +309,39 @@ resources:
       size: { get_param: volume_size }
       availability_zone: { get_param: availability_zone }
       volume_type: { get_param: volume_type }
+
   volume_attachment:
     type: OS::Cinder::VolumeAttachment
     properties:
       volume_id: { get_resource: cinder_volume }
       instance_uuid: { get_resource: user_data_instance }
-      mountpoint: /dev/vdb
+      mountpoint: null
 
-  user_data_instance_port:
-    type: OS::Neutron::Port
-    properties:
-      network_id: { get_param: net_id }
-      security_groups: { get_param: security_groups }
 
 outputs:
-  instance_ip:
-    description: The IP address of the deployed instance
-    value: { get_attr: [user_data_instance, first_address] }
   instance_id:
     description: Resource ID assigned to the newly created instance
     value: { get_resource: user_data_instance }
-  manage_url: 
-    description: Pentaho BI Community Edition can be accessed at 
+
+  instance_ips:
+    description: The IP address of the deployed instance
+    value: { get_attr: [user_data_instance, networks] }
+
+  endpoints:
+    description: "Service endpoints"
     value:
-      str_replace:
-        template: http://host:8080/pentaho
-        params:
-          host: { get_attr: [user_data_instance, first_address] } 
+      "Pentaho Web UI":
+        str_replace:
+          params:
+            host: { get_attr: [user_data_instance, first_address] }
+            pentaho_port:
+              get_param: pentaho_port
+          template: "http://host:pentaho_port/pentaho"
+
   postgres_root_passwd:
     description: Password for PostgreSQL root user
     value: {  get_resource: postgres_root_passwd }
+
   pentaho_user_passwd:
     description: Password for pentaho Linux user       
     value: { get_resource: pentaho_user_passwd}
